### PR TITLE
Exclusive should be a wrapper around a reference to the original reso…

### PR DESCRIPTION
**Pull request by korken89**
Exclusive should be a wrapper around a reference to the original resource. Else it becomes quite useless in conjunction with real resources.

This was noticed when moving RTFM to `mutex_trait`, see here: https://github.com/rtfm-rs/cortex-m-rtfm/blob/8073f648cfc967d9efbb2f936e3f0e10a580a64f/examples/generics.rs#L50
(this currently does not compile as we are not taking a reference to the original resource)

### CODE REVIEW

**Review by jonas-schievink — APPROVED** [review]
Makes sense to me. I don't think there's really any use case for a by-value `Exclusive`, so this seems better.

bors r+

**Review by therealprof — APPROVED** [review]
LGTM

**Pull request merged**
